### ISSUE TITLE
PHP56 failed to build on 10.10.2

### ISSUE THREAD

**Issue by pdechanoz** [Homebrew/homebrew-php#1631]
Upgrading php56
./configure --prefix=/usr/local/Cellar/php56/5.6.7 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr
==> make
_zif_pg_lo_truncate in pgsql.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....

https://gist.github.com/626bd9cf19d107ffe481

**Comment by alanthing** [comment]
What version were you upgrading from? How was the previous version built?

**Comment by pdechanoz** [comment]
My version :

PHP 5.6.6 (cli) (built: Feb 20 2015 06:10:17) (DEBUG)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

This version was built using the same way (brew upgrade)

**Comment by alanthing** [comment]
What options did you use with `brew install php56` originally?

**Comment by pdechanoz** [comment]
brew install php56 --with-debug --with-fpm --with-intl --with-pgsql --without-apache

brew install php56-apcu php56-geoip php56-imagick php56-mcrypt  php56-xdebug

PS : the xcode's version has changed between the built

**Comment by alanthing** [comment]
Thanks. I'm suspecting a problem with the debug settings in php55 and php56 so I'll take a look at that.

For what it's worth: `--with-fpm` is no longer needed, we include that by default. We're also building the Apache module, but it only creates a self-contained .so file that does not interfere with anything outside of the build directory, so you might as well leave that out for simplicity. I also think `--with-debug` is on by default but I'm suspecting that's the problem. We've also had other users mention `--with-pgsql` giving them issue.

For the sake of being thorough... how did you install Postgres? Through Homebrew or the project's installer?

**Comment by pdechanoz** [comment]
With brew

**Comment by Krinkle** [comment]
Also failing here:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C109

$ brew upgrade php56
==> Installing php56
==> Downloading https://www.php.net/get/php-5.6.7.tar.bz2/from/this/mirror
######################################################################## 100.0%
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.7 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr/local/etc/php/5.6 --with-config-file-scan-dir=/usr/l
checking for gzgets in -lz... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues
```

**Comment by hmert** [comment]
#1629

**Comment by jimigrunge** [comment]
@Krinkle I had the same issue and error. Re-istalled the command line tools with "xcode-select --install" and php 5.6.7 installed without issue

**Comment by Krinkle** [comment]
@jimigrunge Thanks! Worked like a charm. Ran `brew uninstall php56 && brew install php56` and everything went great.

**Comment by alanthing** [comment]
Since @pdechanoz opened this, I'm going to focus on his issue. Others should create separate issues as it is rare with this project that issues are truly unique due to many environmental differences. 

@pdechanoz, I believe the issue you're seeing is that you added compile options to PHP which force a from-source build, and you have debug options enabled. Then, some of the extensions you're adding on may not be built from source and instead use pre-built binary bottles which would not have debug options enabled. I would suggest uninstalling all PHP formula (you won't lose config settings in /usr/local/etc) and re-installing with the `--build-from-source` flag on everything. 

I'll close this issue for now but reply back if you continue to have issues despite these instructions. As for others- please open new issues.
