### ISSUE TITLE
php5*-libvirt fails to compile on OS X 10.11

### ISSUE THREAD

**Issue by ablyler** [Homebrew/homebrew-php#2149]
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
/bin/sh ../libtool  --tag=CC   --mode=link clang -I/usr/local/Cellar/php56/5.6.13_2/include/php -I/usr/local/Cellar/php56/5.6.13_2/include/php/main -I/usr/local/Cellar/php56/5.6.13_2/include/php/TSRM -I/usr/local/Cellar/php56/5.6.13_2/include/php/Zend -I/usr/local/Cellar/php56/5.6.13_2/include/php/ext -I/usr/local/Cellar/php56/5.6.13_2/include/php/ext/date/lib -I/usr/local/Cellar/libxml2/2.9.2/include/libxml2  -I/usr/local/Cellar/libvirt/1.2.19/include  -I/usr/local/Cellar/libvirt/1.2.19/include  -DHAVE_CONFIG_H -I../winsrc -DCOMPILE_DL_LIBVIRT=1 -g -O2  -L/usr/local/Cellar/libxml2/2.9.2/lib -lxml2  -L/usr/local/Cellar/libvirt/1.2.19/lib -lvirt  -L/usr/local/Cellar/libvirt/1.2.19/lib -lvirt-qemu -lvirt   -o libvirt-php.la -rpath /usr/local/Cellar/php56-libvirt/HEAD/lib libvirt_php_la-vncfunc.lo libvirt_php_la-sockets.lo libvirt_php_la-libvirt-php.lo
libtool: link: clang -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libvirt-php.0.dylib  .libs/libvirt_php_la-vncfunc.o .libs/libvirt_php_la-sockets.o .libs/libvirt_php_la-libvirt-php.o   -L/usr/local/Cellar/libxml2/2.9.2/lib -lxml2 -L/usr/local/Cellar/libvirt/1.2.19/lib -lvirt-qemu -lvirt  -g -O2   -install_name  /usr/local/Cellar/php56-libvirt/HEAD/lib/libvirt-php.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
duplicate symbol _gdebug in:
    .libs/libvirt_php_la-vncfunc.o
    .libs/libvirt_php_la-sockets.o
duplicate symbol _gdebug in:
    .libs/libvirt_php_la-vncfunc.o
    .libs/libvirt_php_la-libvirt-php.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
