### ISSUE TITLE
php56 failed to build on 10.11.5

### ISSUE THREAD

**Issue by pafazil** [Homebrew/homebrew-php#3551]
## Description

trying to install openssl into php using these steps: https://www.farces.com/wikis/naked-server/php/php-openssl/

brew fails to build php56 with openssl
## Context and Logs

https://gist.github.com/anonymous/f078271b59668eaa6435cbe156daab7d
Last 15 lines from /Users/mnch/Library/Logs/Homebrew/php56/02.make:
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [libs/libphp5.bundle] Error 1
make: **\* Waiting for unfinished jobs....

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.11.5 OS X El Capitan |
| **Homebrew Version:** | 2.9.3 |
| **PHP Version in use:** | 5.5.34 |
| **Xcode Version:** | 7.3.1 |

**Output of gcc -v:**
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
$ php -v
PHP 5.5.34 (cli) (built: Apr 22 2016 19:16:58) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_
https://gist.github.com/anonymous/f078271b59668eaa6435cbe156daab7d

**Comment by javian** [comment]
Can you do what `brew doctor` suggests a `brew unlink openssl` and try again ?

**Comment by pafazil** [comment]
Gave me the same error.

-
Fazil

**Comment by javian** [comment]
There's a reference to the same error in this issue https://github.com/Homebrew/homebrew-php/issues/1931 but there's no real resolution posted there.

**Comment by javian** [comment]
I can't reproduce it on my system. After unlinking openssl could you try reinstalling curl in that state before trying to install php ?

**Comment by javian** [comment]
@pafazil did you manage to solve this issue ?

**Comment by pafazil** [comment]
Hi Jan,

Thank you for the responses. No, the issue is not fixed. I tried installing
curl with-openssl but it says curl is already installed. I didn't try
removing and adding it again.

Regards,
Fazil

**Comment by javian** [comment]
You can also do `brew reinstall curl --with-openssl` , it will reinstall curl though but add the openssl option.

**Comment by pafazil** [comment]
Reinstalled curl and ran the php installation. It gave me same error as
before.

**Comment by javian** [comment]
Its a little bit hard to tell form the gist logs but what options are you using for `brew install php56`?

**Comment by pafazil** [comment]
I have tried multiple options, but mainly this one:

brew install php56 --with-apache --with-homebrew-curl
--with-homebrew-libxslt --with-homebrew-openssl --without-snmp

I think it does not like openssl


Regards,

Fazil
