### ISSUE TITLE
php5*-xhgui fails to compile on OS X 10.11

### ISSUE THREAD

**Issue by ablyler** [Homebrew/homebrew-php#2156]
```
==> Installing php56-xhgui from homebrew/homebrew-php
PHP Fatal error:  Function annotation compilation failed for function __construct in file - at line 535, error message: No phpdoc specified - all constructors with arguments require phpdoc. (Did you remember to use /** ?)
 in Unknown on line 0
composer: Composer PHP requirements check has failed. The following verification command:

    curl -s http://getcomposer.org/installer | /usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off -d date.timezone=UTC -d apc.enable_cli=Off -- --check

failed because of the following reason:


    Fatal error: Function annotation compilation failed for function __construct in file - at line 535, error message: No phpdoc specified - all constructors with arguments require phpdoc. (Did you remember to use /** ?)
     in Unknown on line 0
```

**Comment by ablyler** [comment]
This was due to having `php56-augmentedtypes` installed.  Invalid.
