### ISSUE TITLE
php72 after update enchant to 2.1.2 error

### ISSUE THREAD

**Issue by nohnaimer** [Homebrew/homebrew-php#4650]
## Description
```
brew upgrade --cleanup
php -v
dyld: Library not loaded: /usr/local/opt/enchant/lib/libenchant.1.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6
```

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.13.2
**Homebrew version:**   | 1.4.0
**PHP version in use:** | 7.2.0_11
**Xcode version:**      | Xcode 9.2 Build version 9C40b

**Output of `gcc -v`:**
```
gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of `php -v`:**
```
php -v
dyld: Library not loaded: /usr/local/opt/enchant/lib/libenchant.1.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6
```

Any ideas? Thank you!

**Comment by SMillerDev** [comment]
This happens when dependency names change. The solution is to reinstall php from source so it links to the new files.

**Comment by nohnaimer** [comment]
```
brew reinstall php72
==> Reinstalling homebrew/php/php72 --with-enchant --with-gmp --with-webp --with-postgresql --with-argon2 --wi
==> Downloading https://php.net/get/php-7.2.0.tar.bz2/from/this/mirror
Already downloaded: /Users/and1/Library/Caches/Homebrew/php72-7.2.0
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php72/7.2.0_11 --localstatedir=/usr/local/var --sysconfdir=/usr/loc
==> make
Last 15 lines from /Users/and1/Library/Logs/Homebrew/php72/02.make:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
Undefined symbols for architecture x86_64:
  "_enchant_dict_add_to_personal", referenced from:
      _zif_enchant_dict_add_to_personal in enchant.o
     (maybe you meant: _zif_enchant_dict_add_to_personal)
  "_enchant_dict_free_suggestions", referenced from:
      _zif_enchant_dict_suggest in enchant.o
      _zif_enchant_dict_quick_check in enchant.o
  "_enchant_dict_is_in_session", referenced from:
      _zif_enchant_dict_is_in_session in enchant.o
     (maybe you meant: _zif_enchant_dict_is_in_session)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/phpdbg/phpdbg] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting.html

These open issues may also help:
php72 after update enchant to 2.1.2 error https://github.com/Homebrew/homebrew-php/issues/4650
php72 --with-pdo-oci compiles successfully but breaks apache https://github.com/Homebrew/homebrew-php/issues/4646
php72 install with debug & enchant options + phalcon 3.2.0 may got 502 bad gateway https://github.com/Homebrew/homebrew-php/issues/4649
php72-uuid 1.0.4 (new formula) https://github.com/Homebrew/homebrew-php/pull/4247
```

**Comment by nohnaimer** [comment]
Without **--with-enchant** working as it should.
With **--with-enchant**
```
Last 15 lines from /Users/and1/Library/Logs/Homebrew/php72/02.make:
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
Undefined symbols for architecture x86_64:
  "_enchant_dict_add_to_personal", referenced from:
      _zif_enchant_dict_add_to_personal in enchant.o
     (maybe you meant: _zif_enchant_dict_add_to_personal)
  "_enchant_dict_free_suggestions", referenced from:
      _zif_enchant_dict_suggest in enchant.o
      _zif_enchant_dict_quick_check in enchant.o
  "_enchant_dict_is_in_session", referenced from:
      _zif_enchant_dict_is_in_session in enchant.o
     (maybe you meant: _zif_enchant_dict_is_in_session)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/phpdbg/phpdbg] Error 1
```

**Comment by SMillerDev** [comment]
It seems PHP needs the 1.x series of enchant. Your 2.x version doesn't work with it. I'm working on a pull request for homebrew core.

**Comment by nohnaimer** [comment]
Maybe!
Thank you!

**Comment by lanlin** [comment]
@nohnaimer i have the same problem.
it seems that after upgrade osx to 10.13.2, there's no /usr/local/opt/enchant/lib/libenchant.1.dylib any more. 
I just find libenchant.2.dylib in that folder, so i have to remove the "--with-enchant"option.
![image](https://user-images.githubusercontent.com/3468024/34026427-fc29cc5c-e190-11e7-866c-3fa5ed456edb.png)

**Comment by nohnaimer** [comment]
@lanlin, This happened after the package was upgraded enchant to version 2.1.2 from version 1. And it seems to be corrected already ...

**Comment by SMillerDev** [comment]
It's not been corrected yet as php is the only project still using version one. So support for enchant might be dropped completely in the future. For now I'm still working on a solution.

**Comment by hylle** [comment]
Having the same problem with php71

```brew reinstall php71 --build-from-source
==> Reinstalling homebrew/php/php71 --with-enchant --with-httpd --with-pear
==> Downloading https://php.net/get/php-7.1.12.tar.bz2/from/this/mirror
Already downloaded: /Users/jh/Library/Caches/Homebrew/php71-7.1.12
Warning: Backing up all known pear.conf and .pearrc files
Warning: If you have a pre-existing pear install outside
         of homebrew-php, or you are using a non-standard
         pear.conf location, installation may fail.
==> ./configure --prefix=/usr/local/Cellar/php71/7.1.12_23 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --with-config-file-path=/usr/local/etc/php/7.1 --with-config
Last 15 lines from /Users/jh/Library/Logs/Homebrew/php71/01.configure:
checking for TCADB support... no
checking for Berkeley DB4 support... no
checking for Berkeley DB3 support... no
checking for Berkeley DB2 support... no
checking for DB1 support... no
checking for DBM support... no
checking for CDB support... builtin
checking for INI File support... builtin
checking for FlatFile support... builtin
checking whether to enable DBA interface... yes
checking whether to enable DOM support... yes
checking for xml2-config path... (cached) /usr/local/opt/libxml2/bin/xml2-config
checking whether libxml build works... (cached) yes
checking for ENCHANT support... yes
configure: error: Cannot find enchant```

**Comment by mikhey** [comment]
I just ran into this today when attempting to upgrade php71.
