### ISSUE TITLE
php failed to build on 10.11

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-php#1941]
_From @yekz on July 28, 2015 8:10_

```
brew install php56
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.6.11.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.11
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.11_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc
==> make
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

_Copied from original issue: Homebrew/homebrew#42197_

**Comment by bfontaine** [comment]
_From @yekz on July 28, 2015 8:50_

php55：
-----
brew install php55
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php55 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.5.27.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.5.27.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.27_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc
==> make
make: *** Waiting for unfinished jobs....
make: *** [sapi/fpm/php-fpm] Error 1
make: *** [sapi/cli/php] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

**Comment by bfontaine** [comment]
Please post the output of `brew gist-logs php56`.

**Comment by yekz** [comment]
https://gist.github.com/2b52b39f6eecce498fb0

i can't open it in china😹

**Comment by christopherdwhite** [comment]
I'm also having this same problem on 10.11.

I tried `brew gist-logs php56` but it's returning: 

`Error: HTTP 403 Forbidden (expected 201)`

Any idea what I'm missing? Apologies, I'm still new to the deep-end.

**Comment by ryanp-me** [comment]
@christopherdwhite When is the last time you ran `brew update`?

**Comment by christopherdwhite** [comment]
I ran `brew cleanup`, `brew update` and `brew upgrade` right before trying to install PHP.

**Comment by ryanp-me** [comment]
Oh, sorry. I didn't look closely enough and thought that was an error downloading PHP. You're likely running into GitHub rate limiting. In order to avoid this, [setup an API key](http://stackoverflow.com/questions/20130681/setting-github-api-token-for-homebrew).

**Comment by christopherdwhite** [comment]
That did it, thanks Ryan! [Here are my logs](https://gist.github.com/anonymous/105e59fa0ec3d3836b07)

**Comment by bfanger** [comment]
If the compile/linker error is:
```
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
```
Try replacing `-lssl` and `-lcrypto` with `/usr/local/opt/openssl/lib/libssl.dylib` and ` /usr/local/opt/openssl/lib/libcrypto.dylib` in the Makefile.

http://stackoverflow.com/questions/31024288/how-to-compile-php-with-openssl-on-os-x-10-9/31734677

**Comment by memuller** [comment]
Same issue here - I'm currently on OSX 10.11 Beta 2, with Xcode 7. 
I thought it had something to do with OpenSSL, but reinstalling it or trying --with-homebrew-libressl had no effect.
Here are my logs:
https://gist.github.com/26fcb6ecc1ee5287c9e1

**Comment by christopherdwhite** [comment]
@bfanger Can you point me to where I need to make that change?

**Comment by alsantos123** [comment]
same here https://gist.github.com/anonymous/cd67449b690b14be543d
OS X 10.11 Beta 15A235d

**Comment by alsantos123** [comment]
File `/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb` line *362*, replace:
```s.change_make_var! "EXTRA_LIBS", "\\1 -lstdc++"```
to
```s.change_make_var! "EXTRA_LIBS", "\\1 -lstdc++ /usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libcrypto.dylib"```

This don't remove `-lssl` and `-lcrypto` witch @christopherdwhite told, I see that the final Makefile was:

```
./Makefile:120:EXTRA_LIBS=-lcrypto -lssl -lcrypto -lz -lexslt -lresolv -ledit -lncurses -lldap -llber -liconv -liconv -lintl -lpng -lz -ljpeg -lcrypto -lssl -lcrypto -lcurl -lbz2 -lz -lcrypto -lssl -lcrypto -lm -lxml2 -lz -licucore -lm -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lcurl -lxml2 -lz -licucore -lm -lfreetype -lodbc -lodbc -lxml2 -lz -licucore -lm -lxml2 -lz -licucore -lm -lxml2 -lz -licucore -lm -lxml2 -lz -licucore -lm -lxml2 -lz -licucore -lm -lxml2 -lz -licucore -lm -lxml2 -lz -licucore -lm -lxml2 -lxslt -lstdc++ /usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libcrypto.dylib
```
but works for me.

**Comment by christopherdwhite** [comment]
Hmm, didn't work for me. [New logs](https://gist.github.com/759fddfc3069187c15da).

**Comment by memuller** [comment]
@alsantos123 's change worked for me; it install without issue now. Thanks!
Sorry to hear it didn't work for you, @christopherdwhite . I'll keep messing around.

**Comment by christopherdwhite** [comment]
You guys are making the change and then just running `brew install php56` right? No intermediate steps?

**Comment by alsantos123** [comment]
Yes @christopherdwhite.
Are you using Xcode beta? Version 7? My version it's beta 3.

**Comment by christopherdwhite** [comment]
That did it, thanks @alsantos123! I was running either beta 1 or beta 2, when I updated to beta 4 PHP built with no problems.

**Comment by jonnybarnes** [comment]
I have this error on OS X 10.11 Public Beta but was running XCode 7 beta 4. Just downloading beta 5 now and will report later if it works.

**Comment by jonnybarnes** [comment]
Updating to XCode 7 beta 5 and making the relavent edit to `abtract-php.rb` worked for me.

**Comment by Hast** [comment]
@jonnybarnes which changes to abstract-php.rb have you done?

**Comment by nesl247** [comment]
The changes by @alsantos123 fixed it for me.

**Comment by Hast** [comment]
Doesn't work for me.
I have downloaded and run XCode 7 Beta 5. But maybe there are more actions I must perform in order to install command line tools from the beta xcode instead of old ones?

**Comment by Hast** [comment]
brew link libxml2 --force Worked for me instead.
See: https://github.com/Homebrew/homebrew-php/issues/1931

**Comment by einfallstoll** [comment]
Install it, if you haven't done so

```
brew install libxml2
brew link libxml2 –force
```

**Comment by Gamec** [comment]
@einfallstoll It helped, thanks for that!

**Comment by SeerUK** [comment]
Currently having a newer issue popping up preventing me from upgrading on 10.11 GM: https://gist.github.com/anonymous/f9232112297a754718bc

**Comment by jeffgeorge** [comment]
@SeerUK That appears to be the issue presently tracked in #2033. It's unable to find libz even if it's already explicitly installed and linked via brew.
